//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineToolMaintenance.Etities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MachineToolMaintenanceEntities : DbContext
    {
        public MachineToolMaintenanceEntities()
            : base("name=MachineToolMaintenanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Repair> Repair { get; set; }
        public virtual DbSet<TypesOfMachines> TypesOfMachines { get; set; }
        public virtual DbSet<TypesOfRepairs> TypesOfRepairs { get; set; }
    }
}
