//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineToolMaintenance.Etities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesOfRepairs
    {
        public int TypesOfRepairsId { get; set; }
        public string TypesOfRepairsTitle { get; set; }
        public int Duration { get; set; }
        public decimal Cost { get; set; }
        public string Note { get; set; }
    }
}
